# **Python DA Assignment 1 - NumPy and Pandas**

## ***NumPy Array Operations***

### **1. Create a 1D NumPy Array**

In [1]:
import numpy as np

In [28]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

### **2. Inspection and Properties**

In [33]:
print(f'Shape {temperatures_w1.shape}')

Shape (7,)

In [32]:
print(f'Data Type {temperatures_w1.dtype}')

Data Type float64

In [36]:
print(f'Number of Elements {temperatures_w1.size}')

Number of Elements 7

### **3. Array Operations**

In [37]:
Fahrenheit = (temperatures_w1 * 9/5) + 32
print(f'Celsius to Fahrenheit {Fahrenheit}')

Celsius to Fahrenheit [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [38]:
print(f'Maximum Temperature {temperatures_w1.max()}')

Maximum Temperature 26.1

In [39]:
print(f'Minimum Temperature {temperatures_w1.min()}')

Minimum Temperature 20.8

In [40]:
print(f' Average Temperature {round(temperatures_w1.mean(),1)}')

 Average Temperature 23.5

### **4. Array Slicing and Indexing**

In [46]:
print(f'First Three days Temperature {temperatures_w1[0:3]}')

First Three days Temperature [22.5 25.3 20.8]

In [47]:
print(f'last Two days Temperature {temperatures_w1[-2:]}')

last Two days Temperature [24.8 21.9]

In [51]:
print(f'Middle three days Temperature {temperatures_w1[2:5]}')

Middle three days Temperature [20.8 23.4 26.1]

### **5. Create a 2D Array**

In [52]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

### **6. Inspect and Slice the 2D Array**

In [53]:
print(f'Shape {temperatures.shape}')

Shape (2, 7)

In [54]:
print(f'Data Type {temperatures.dtype}')

Data Type float64

In [55]:
print(f'Total Number of Elements {temperatures.size}')

Total Number of Elements 14

In [60]:
print(f'last two days for both Weeks: \n{temperatures[ : , 5 : ]}')

last two days for both Weeks:
[[24.8 21.9]
 [22.8 20.1]]

## ***Pandas Series***

### **1. Creating Pandas Series**

In [61]:
import pandas as pd

In [66]:
marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'], name='Marks')
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: Marks, dtype: int64

### **2. Indexing and Slicing**

In [70]:
print(f'1st Rank Student Mark {marks.iloc[0]}')

1st Rank Student Mark 95

In [73]:
print(f'Top 3 Ranks Mark: \n{marks.loc['Rank1' : 'Rank3']}')

Top 3 Ranks Mark:
Rank1    95
Rank2    92
Rank3    89
Name: Marks, dtype: int64

In [74]:
print(f'3rd Rank Student Mark {marks.iloc[2]}')

3rd Rank Student Mark 89

In [79]:
print(f'Marks are Greater than 90 \n{marks[marks > 90]}')

Marks are Greater than 90
Rank1    95
Rank2    92
Name: Marks, dtype: int64

### **3. Manipulating Series**

In [85]:
marks.loc['Rank1'] = 100
print(f'Updated Marks: \n{marks}')

Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
Name: Marks, dtype: int64

In [86]:
del marks['Rank5']
print(f'Updated Marks: \n{marks}')

Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: Marks, dtype: int64

In [89]:
CGPA = marks/10
print(f'CGPA: \n{CGPA}')

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Name: Marks, dtype: float64

## ***Pandas DataFrame***

### **1. Creating Pandas DataFrame**

In [169]:
transactions = pd.DataFrame({'TransactionID' : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                             'ProductCategory' : ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                             'Region' : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                             'Amount' : [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
                             })
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### **2. Data Exploration**

In [91]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [92]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [96]:
print(f'Shape {transactions.shape}')

Shape (10, 4)

In [99]:
print(f'Columns {transactions.columns}')

Columns Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [102]:
print(f'Data Types: \n{transactions.dtypes}')

Data Types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [106]:
print(f'ProductCategory and Amount Columns: \n\n{transactions[['ProductCategory', 'Amount']]}')

ProductCategory and Amount Columns:

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [111]:
print(f'Last 3 Columns: \n\n{transactions.iloc[ : , -3 : ]}')

Last 3 Columns:

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [119]:
transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [115]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [122]:
print(f'Region {transactions['Region'].unique()}')

Region ['North' 'South' 'East' 'West']

In [123]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

### **3. Manipulating the DataFrame**

In [171]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [172]:
transactions['Discount'] = transactions['Amount']/10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [173]:
transactions.drop(transactions[transactions['TransactionID'] == 109].index,inplace=True)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [175]:
del transactions['Discount']
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400